export const CLOSE_ALBUM = "CLOSE_ALBUM";
export const OPEN_ALBUM = "OPEN_ALBUM";
export const CLOSE_ALL_ALBUMS = "CLOSE_ALL_ALBUMS";
export const OPEN_ALL_ALBUMS = "OPEN_ALL_ALBUMS";
export const SET_SONGS_BY_ALBUMS = "SET_SONGS_BY_ALBUMS";
export const SET_ALBUMS_KEYS = "SET_ALBUMS_KEYS";
